config/routes.rb
Portfolio::Application.routes.draw do

resources :posts do
  resources :comments
end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :projects

  root :to => 'home#index'
  match 'home' => 'home#index'
  match 'contact' => 'home#contact'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :approved, :author, :author_email, :author_url, :content, :referrer, :user_agent, :user_ip

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :published
  validates_presence_of :title, :content
  belongs_to :author, class_name: "User"

  validates :title, presence: true
  validates :url, presence: true
  validates :description, presence: true


  def publish!
    published = true
    save!
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :technologies_used

  validates :technologies_used, presence: true
  validates :name, length: {in: 4..255}
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :role, :published, :email, :password, :password_confirmation, :remember_me

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :title, :body


  has_many :posts, foreign_key: "author_id"

  def author?
    role == 'author'
  end

  def editor?
    role == 'editor'
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.nickname
    user.email = "#{user.name}@twitter.example.com"
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to request.headers["Referer"] || root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # We use a before_filter to find the @post.
  #
  before_filter :find_the_post

  # GET /posts/1/comments
  def index
    @comments = @post.comments
  end

  # GET /posts/1/comments/1
  def show
    @comment = @post.comments.find(params[:id])
  end

  # GET /posts/1/comments/new
  def new
    @comment = @post.comments.build
  end

  # GET /posts/1/comments/1/edit
  def edit
    @comment = @post.comments.find(params[:id])
  end

  # POST /posts/1/comments
  def create
    @comment = @post.comments.build(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@post, @comment], notice: 'Comment was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /posts/1/comments/1
  def update
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to [@post, @comment], notice: 'Comment was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /posts/1/comments/1
  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_comments_path(@post) }
    end
  end

  private
  def find_the_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "#{user.name}, you are signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter , :all
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    # @comments = @post.comments

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    authorize @post
    respond_to do |format|
      if @post.save
        current_user.posts << @post
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }

      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    @post = Post.find(params[:id])
    authorize @post, :update?
    @post.publish!
    redirect_to @post
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(params[:project])
		if @project.save
			flash[:notice] = "Project was successfully added"
			redirect_to @project
		else
			flash[:alert] = "Project could not be saved"
			render action: "new"
		end
	end

	def show
		@project = Project.find(params[:id])
	end

	def edit
		@project = Project.find(params[:id])
	end

	def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_path }
      format.json { head :no_content }
    end
  end

	def update
		@project = Project.find(params[:id])
		if @project.update_attributes(params[:project])
			redirect_to @project, notice: 'Project was successfully updated.'
		else
			render action: "edit"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # translate the rails flash levels to appropriate twitter bootstrap css classes
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" style="background-image:url('http://blog.bounceweb.com/wp-content/uploads/2010/09/Tools-for-Ruby-on-Rails-logo.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://i.imgur.com/KLkLxBC.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://fc02.deviantart.net/fs71/f/2012/037/c/4/css3_wallpaper_2_by_neersighted-d4ox1cr.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://prasadprechu.files.wordpress.com/2013/01/twitter-bootstrap-website-for-inspiration-cssauthor-com.png?w=657&h=277');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://fc06.deviantart.net/fs71/f/2011/026/9/2/html_5_wallpaper_by_bqra-d382muo.jpg');"></div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</div>

app/views/application/_footer.html.erb
<div class="container">

  <hr>

  <footer>
    <div class="row">
      <div class="col-lg-12">
      </div>
    </div>
  </footer>

</div><!-- /.container -->

app/views/application/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->

    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', home_path%></li>
        <li><%= link_to 'Blog', posts_path %></li>
        <li><%= link_to 'Projects', projects_path %></li>
        <li><%= link_to 'Contact', contact_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login<b class="caret"></b></a>
          <ul class="dropdown-menu">
          <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
           <li><%= link_to 'Sign Up', new_user_registration_path %></li>
           <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/comments/show.html.erb
<h5>Comments: </h5>
<ul>
  <% @post.comments.each do |comment| %>
    <li><%= comment.body %></li>
  <% end %>
</ul>

app/views/home/_footer.html.erb
<div class="container">

  <hr>

  <footer>
    <div class="row">
      <div class="col-lg-12">

      </div>
    </div>
  </footer>

</div><!-- /.container -->

app/views/home/contact.html.erb
<!-- Page Content -->

<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header">Contact <small>I would Love to Hear From You!</small></h1>
    </div>

    <div class="col-lg-12">
      <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
      <iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=seattle+washington&amp;ie=UTF8&amp;hq=&amp;hnear=Seattle,+King,+Washington&amp;gl=us&amp;t=m&amp;ll=47.613223,-122.326412&amp;spn=0.055547,0.109863&amp;z=13&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?q=seattle+washington&amp;ie=UTF8&amp;hq=&amp;hnear=Seattle,+King,+Washington&amp;gl=us&amp;t=m&amp;ll=47.613223,-122.326412&amp;spn=0.055547,0.109863&amp;z=13&amp;source=embed" style="color:#0000FF;text-align:left">View Larger Map</a></small>

    </div><!-- /.row -->
    <div class="col-sm-4">
      <h3>Marshall Lanners</h3>

      <p>
        <br>
        Seattle, WA 98122<br>
      </p>
      <p><i class="icon-phone"></i> <abbr title="Phone">P</abbr>: <a href = "tel:+18052689701">(805) 268-9701</a></p>
      <p><i class="icon-envelope-alt"></i> <abbr title="Email">E</abbr>: <a href="mailto:lanners.marshall@yahoo.com">lanners.marshall@yahoo.com</a></p>
      <ul class="list-unstyled list-inline list-social-icons">
        <li class="tooltip-social facebook-link"><a href="#facebook-page" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="icon-facebook-sign icon-2x"></i></a></li>
        <li class="tooltip-social linkedin-link"><a href="#linkedin-company-page" data-toggle="tooltip" data-placement="top" title="LinkedIn"><i class="icon-linkedin-sign icon-2x"></i></a></li>
        <li class="tooltip-social twitter-link"><a href="#twitter-profile" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="icon-twitter-sign icon-2x"></i></a></li>
        <li class="tooltip-social google-plus-link"><a href="#google-plus-page" data-toggle="tooltip" data-placement="top" title="Google+"><i class="icon-google-plus-sign icon-2x"></i></a></li>
      </ul>
    </div>

  </div><!-- /.row -->

</div><!-- /.container -->

<!-- Bootstrap core JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">About Me</h2>
      <ul id="myTab" class="nav nav-tabs">
        <li class="active"><a href="#service-one" data-toggle="tab">Education</a></li>
        <li><a href="#service-two" data-toggle="tab">Skills</a></li>
        <li><a href="#service-three" data-toggle="tab">Hobbies</a></li>
        <li><a href="#service-five" data-toggle="tab">Interests</a></li>
      </ul>
      <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade in active" id="service-one">
          <i class="icon-gear pull-left icon-4x"></i>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam placerat nunc ut tellus tristique, non posuere neque iaculis. Fusce aliquet dui ut felis rhoncus, vitae molestie mauris auctor. Donec pellentesque feugiat leo a adipiscing. Pellentesque quis tristique eros, sed rutrum mauris.</p>
          <p>Nam fringilla quis enim in eleifend. Suspendisse sed lectus mauris. Nam commodo, arcu et posuere placerat, tellus tortor dignissim eros, sit amet eleifend urna lorem sit amet nulla. Praesent sem nibh, vulputate nec congue eu, dapibus vitae augue. Suspendisse cursus urna sit amet metus porttitor, in pharetra quam feugiat. Etiam tempus euismod nulla eget pellentesque.</p>
        </div>
        <div class="tab-pane fade" id="service-two">
          <i class="icon-gears pull-left icon-4x"></i>
          <p>Nam fringilla quis enim in eleifend. Suspendisse sed lectus mauris. Nam commodo, arcu et posuere placerat, tellus tortor dignissim eros, sit amet eleifend urna lorem sit amet nulla. Praesent sem nibh, vulputate nec congue eu, dapibus vitae augue. Suspendisse cursus urna sit amet metus porttitor, in pharetra quam feugiat. Etiam tempus euismod nulla eget pellentesque.</p>
          <p>Vestibulum laoreet molestie urna ac vehicula. Phasellus laoreet semper ipsum ac gravida. Sed in varius tortor. Nullam blandit in neque quis aliquet. Fusce volutpat pellentesque sem non convallis. Suspendisse sit amet magna pulvinar, gravida mauris eu, tincidunt massa. Nam lectus mi, viverra non quam nec, mollis malesuada dolor. Vivamus hendrerit nunc interdum turpis egestas, a lobortis odio consequat. Fusce posuere purus quis ligula faucibus lacinia. Curabitur sit amet congue dolor. Duis dapibus hendrerit nunc et gravida. Phasellus mollis, lectus quis ornare aliquam, arcu orci posuere lectus, vehicula bibendum sem ante quis lacus.</p>
        </div>
        <div class="tab-pane fade" id="service-three">
          <i class="icon-magic pull-left icon-4x"></i>
          <p>Vestibulum laoreet molestie urna ac vehicula. Phasellus laoreet semper ipsum ac gravida. Sed in varius tortor. Nullam blandit in neque quis aliquet. Fusce volutpat pellentesque sem non convallis. Suspendisse sit amet magna pulvinar, gravida mauris eu, tincidunt massa. Nam lectus mi, viverra non quam nec, mollis malesuada dolor. Vivamus hendrerit nunc interdum turpis egestas, a lobortis odio consequat. Fusce posuere purus quis ligula faucibus lacinia. Curabitur sit amet congue dolor. Duis dapibus hendrerit nunc et gravida. Phasellus mollis, lectus quis ornare aliquam, arcu orci posuere lectus, vehicula bibendum sem ante quis lacus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam placerat nunc ut tellus tristique, non posuere neque iaculis. Fusce aliquet dui ut felis rhoncus, vitae molestie mauris auctor. Donec pellentesque feugiat leo a adipiscing. Pellentesque quis tristique eros, sed rutrum mauris.</p>
        </div>
        <div class="tab-pane fade" id="service-four">
          <i class="icon-beaker pull-left icon-4x"></i>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam placerat nunc ut tellus tristique, non posuere neque iaculis. Fusce aliquet dui ut felis rhoncus, vitae molestie mauris auctor. Donec pellentesque feugiat leo a adipiscing. Pellentesque quis tristique eros, sed rutrum mauris.</p>
          <p>Nam fringilla quis enim in eleifend. Suspendisse sed lectus mauris. Nam commodo, arcu et posuere placerat, tellus tortor dignissim eros, sit amet eleifend urna lorem sit amet nulla. Praesent sem nibh, vulputate nec congue eu, dapibus vitae augue. Suspendisse cursus urna sit amet metus porttitor, in pharetra quam feugiat. Etiam tempus euismod nulla eget pellentesque.</p>
        </div>
        <div class="tab-pane fade" id="service-five">
          <i class="icon-flag pull-left icon-4x"></i>
          <p>Nam fringilla quis enim in eleifend. Suspendisse sed lectus mauris. Nam commodo, arcu et posuere placerat, tellus tortor dignissim eros, sit amet eleifend urna lorem sit amet nulla. Praesent sem nibh, vulputate nec congue eu, dapibus vitae augue. Suspendisse cursus urna sit amet metus porttitor, in pharetra quam feugiat. Etiam tempus euismod nulla eget pellentesque.</p>
          <p>Vestibulum laoreet molestie urna ac vehicula. Phasellus laoreet semper ipsum ac gravida. Sed in varius tortor. Nullam blandit in neque quis aliquet. Fusce volutpat pellentesque sem non convallis. Suspendisse sit amet magna pulvinar, gravida mauris eu, tincidunt massa. Nam lectus mi, viverra non quam nec, mollis malesuada dolor. Vivamus hendrerit nunc interdum turpis egestas, a lobortis odio consequat. Fusce posuere purus quis ligula faucibus lacinia. Curabitur sit amet congue dolor. Duis dapibus hendrerit nunc et gravida. Phasellus mollis, lectus quis ornare aliquam, arcu orci posuere lectus, vehicula bibendum sem ante quis lacus.</p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

<div class="container">
  <div class="col-lg-12">
    <h1 class="page-header">Welcome aboard<small><FONT COLOR="red"> You're riding My Website</FONT></small></h1>
  </div>
  <div class="row">
    <div class="col-md-8">
      <img src="http://upload.wikimedia.org/wikipedia/commons/1/16/Seattle_4.jpg" height= "400" width="700"/>
    </div>

    <div class="col-md-4">
      <h3>Marshall Bio</h3>
      <p>I'm a code junkie living in the greater Seattle area. I enjoy Ruby on Rails, html, css, javascript and more. What to know more about me? Want to see my work?Come check out my site!</p>
    </div>

  </div>

  <div class="row">

    <div class="col-lg-12">
      <h3 class="page-header">My Social Media</h3>
    </div>

    <div class="col-sm-3 col-xs-6">
      <a href="https://github.com/cheatermoves">
       <img src="https://github.global.ssl.fastly.net/images/modules/logos_page/Octocat.png" width="260" height="170">
     </a>
   </div>

   <div class="col-sm-3 col-xs-6">
    <a href="https://twitter.com/lanners_cool">
     <img src="https://si0.twimg.com/profile_images/2284174758/v65oai7fxn47qv9nectx.png" width="260" height="170">
   </a>
 </div>

 <div class="col-sm-3 col-xs-6">
  <a href="http://www.linkedin.com/in/mlanners">
   <img src="http://blogs.nature.com/naturejobs/files/2012/12/LinkedIn-InBug-2CRev.png" width="260" height="170">
 </a>

</div>

<div class="col-sm-3 col-xs-6">
  <a href="https://www.facebook.com/marshall.lanners">
    <img src="http://www.3martinilunches.com/Portals/206831/images/facebook_logo.png" width="260" height="190">
  </a>
</div>
</div>
</div>

<div id="clouds">
  <div class="cloud x1"></div>
  <!-- Time for multiple clouds to dance around -->
  <div class="cloud x2"></div>
  <div class="cloud x3"></div>
  <div class="cloud x4"></div>
  <div class="cloud x5"></div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">About Code Fellows<small></small></h1>

      <div class="row">
        <div class="col-md-6">
         <a href="https://www.codefellows.org/new-website-coming-soon"><img src="http://media.tumblr.com/608fb9bb269acce17f4f2f0eac66804b/tumblr_inline_mkro6saay01qz4rgp.jpg"/></a>
       </div>
       <div class="col-md-6">
        <h3>Ruby on Rails</h3>


        <p>I am a code fellow who recently took the intensive <FONT COLOR="red">RUBY ON RAILS</FONT> program. Is RAILS awesome? You bet! This website is build in RAILS. What is there to say about myself? Until Code fellows I was largly self taught in HTML, CSS, and Javascript. Is computer programming hard? No doubt! But its super fun and rewarding at the same time.</p>
      </div>

    </div>

    <!-- Team Member Profiles -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>


<body>

  <%= render 'nav' %>

  <%= render 'carousel' %>
  <div class="container">
    <div class="section">
      <div class"container">
        <div class ="row">
          <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %>">
            <%= value %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div>
    <%= yield %>
  </div>

  <%= render 'footer' %>
</body>
</html>

app/views/posts/_form.html.erb
<div class="container">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>Listing posts</h1>

  <table>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

<% @posts.each do |post| %>
  <tr id="<%= dom_id(post) %>">
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <% if policy(post).update? %>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <% end %>
    <% if policy(post).publish? %>
    <td><%= button_to "Publish", post_path(post, post: {published: true}), method: :put, class: "btn" %> </td>
    <% end %>
    <% if policy(post).destroy? %>
      <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
  </table>
  <br />
  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container">

<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/projects/index.html.erb
<div class="container">
<% @projects.each do |project| %>
  <div class="project" id="<%= dom_id(project) %>">
    <h3><%= project.name %></h3>
    <p><%= project.technologies_used %></p>
    <div class="nav">
      <%= link_to 'Show', project %> |
      <%= link_to 'Edit', edit_project_path(project) %> |
      <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

<br />
<%= link_to 'New project', new_project_path %>
</div>